---
title: "UKHSA report"
format: html
---

## Introduction

Influenza is a highly infectious and rapidly evolving respiratory virus circulating seasonally around the world [@cope2018]. The World Health Organisation (WHO) estimates that between 290000-650000 deaths occur due to the respiratory virus, not including deaths not due to secondary infections caused by influenza [@WHO2022]. Antigenic shifts in the virus may result in uncontrolled extensive spread causing an epidemic (e.g. 1918-2009) [@cope2018]

Serious progression of the virus may lead to deaths in at risk groups such as children \<2 y.o., pregnant women, people \>65 y.o. and people with underlying medical conditions, [@zarocostas2009]. In a UK context, seasonal influenza circulation puts a burden on NHS especially hospital beds and GP services [@cope2018]. Having more data to help plan for seasonal peaks can help alleviate pressure on vital services.

someone please help and put in the first graphic around here

### Who is UKHSA and why are they interested 

UK Health Security Agency (UKHSA) was created as a successor to Public Health England in April 2021 cite. Set up during the height of the COVID-19 pandemic, the UKHSA's main priority is to tackle national health threats through the use of data analytics and developing vaccines cite.

Understanding the data of how flu is spread can help assist in planning vaccination roll-out. Vaccination is greatly beneficial as it averts between 180,000 and 626,000 cases of influenza per year in England, helping prevent between 5,678 and 8,800 premature deaths [@franklin2018]. Furthermore, every death averted due to vaccination is estimated to save the NHS £50,610 [@franklin2018].

In the UK there are three main ways that influenza is reported: through primary care data, hospitalisation and through swabbing programmes. Having three separate data sources is a valuable to compare whether the peak in the seasonal spread is in the same week or whether any of the data sources lag the others - identifying a possible prediction of a peak in hospitalisations for example. also knowing what strains and what age group is being hit by the flu initially may be useful to bla bla bla.

### Research question and hypothesis

What is the temporal relationship between different influenza data sources (lab-confirmed infections, GP consultations, hospitalisations) in the UK, and have these changed in 2022/3 compared to the pre-pandemic years 2016-2019?

We defined our Qs to address these issues.

Hypothesis - There could be a time delay betw one source of surveillance and another. And the scale of the one that peaks earlier might be predictive of the later ones. There are changes in reporting procedures for resp infections post-covid. Children may precede adults due to mixing .

## Methods

methods for R nought (or effective) can be cited from Lipsitch

## Data sources and extraction

## Results

### Source

### Season

### Log graphs and $R_0$ value

### Stratified by Flu strain type

## Discussion

## Conclusion

## References
